### ISSUE TITLE
feature request: annotate NIRCam SW SCA labels onto segment ID mosaic

### ISSUE THREAD

**Issue by mperrin** [spacetelescope/wss_tools#46]
A small user convenience: For the segment ID feature, it would be nice if the labels A1 - B4 were drawn or annotated onto the screen. I.e. with matplotlib `Text` artists drawn on top of the actual FITS image, in the appropriate locations.

**Comment by mperrin** [comment]
I will give a shot at implementing this myself. (partly as a test exercise to learn how the code internals work here.)

**Comment by mperrin** [comment]
It would also be convenient if all of these images started out with the 'zoom to fit' zoom setting applied by default.

**Comment by pllim** [comment]
Rather than using matplotlib, I would advise to use Ginga's own objects first, if possible. Ginga's API doc is not that great, so you might have to code dive a bit over there. If you can find it, please let me know. Thanks!

**Comment by pllim** [comment]
Implemented in #47
