### ISSUE TITLE
Add function to generate operation file  

### ISSUE THREAD

**Issue by Skyhawk172** [spacetelescope/wss_tools#50]
In some cases, users will want to launch QUIP from the command line, which requires the generation of an operation file.  Currently, the WSS WEx handles the generation of the file when QUIP is started.  A new function shall therefore be created that will allow the user to generate such an operation file. 

This discussion was started earlier where Pey-Lian already made some suggestions as to where and how to implement this function. See https://github.com/spacetelescope/wss_tools/pull/49#pullrequestreview-211989547

As discussed, Pey-Lian will lead the development of this new function.

**Comment by pllim** [comment]
I have a working solution (PR forthcoming). The only thing I cannot duplicate (without much more effort) is the exact `<?xml version="1.0" encoding="UTF-8" standalone="yes"?>` header. What I create only has `<?xml version="1.0"?>` (without "encoding" or "standalone" info). Is this okay with you? Do you use it for anything? I am still able to get QUIP to work without those info.

**Comment by Skyhawk172** [comment]
If the QUIP doesn't use it to run, then we don't need as far as I can tell.

**Comment by pllim** [comment]
Please review #55 to see if you are okay with the API. Or even take it for a spin if you want to. Thanks!
