### ISSUE TITLE
Does QUIP need to support ASDF?

### ISSUE THREAD

**Issue by pllim** [spacetelescope/wss_tools#61]
@Skyhawk172 or @mperrin , is QUIP required to work with JWST ASDF format? I might have asked this a long time ago and I think the answer back then was "no," has this answer changed? Please advise, thanks!

**Comment by mperrin** [comment]
It's still no. The WSS can only handle FITS files and there is no plans to ever update it for ASDF.

**Comment by pllim** [comment]
Okay, good to know. Thanks for the swift response!
